### ISSUE TITLE
Select logger level at startup

### ISSUE THREAD

**Issue by CuriousDolphin** [FocoosAI/focoos#9]

**Comment by giuseppeambrosio97** [comment]
`

@cache
def get_logger(name="focoos", level=logging.DEBUG):
    logger = logging.getLogger(name)
    logger.setLevel(level)
    return logging.getLogger(name)


def setup_logging():
    logging.config.dictConfig(LOGGING_CONFIG)
    logger = get_logger()
    return logger
`
